services:
  web-app: 
    image: rojasvictor/node-project:v1
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    depends_on:
      - db
    networks: 
      red_web:
        ipv4_address: 192.168.10.10
      red_interna:
        ipv4_address: 192.168.20.10
    ports:
      - "8080:3000"
  db:
    image: postgres:18rc1-alpine3.22
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes: 
      - db-data:/var/lib/postgresql/data
    networks: 
      red_interna:
          ipv4_address: 192.168.20.20
    ports:
      - "5432:5432"

volumes:
  db-data:

networks:
  red_web:
    ipam:
      config:
        - subnet: 192.168.10.0/24
  red_interna:
    ipam:
      config:
        - subnet: 192.168.20.0/24