# WordPress Moderno con Docker COmpose V2+
services:
  wordpress:
    image: wordpress:php8.2-apache
    container_name: wp-web
    deploy:
       resources:
          limits:
            cpus: '1'
            memory: 512M
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: /run/secrets/db_user
      WORDPRESS_DB_PASSWORD: /run/secrets/db_pass
      WORDPRESS_DB_NAME: /run/secrets/db_name
    volumes:
      - wp_data:/var/www/html
      - ./wp-content:/var/www/html/wp-content  # Para desarrollo personalizado
    depends_on:
      db:
        condition: service_healthy
    networks:
      - wp_network

  db:
    image: mariadb:11.3
    container_name: wp-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/db_root_pass
      MYSQL_DATABASE: /run/secrets/db_name
      MYSQL_USER: /run/secrets/db_user
      MYSQL_PASSWORD: /run/secrets/db_pass
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -u$$(cat /run/secrets/db_user) -p$$(cat /run/secrets/db_pass)"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - wp_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: wp-admin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER_FILE: /run/secrets/db_user
      PMA_PASSWORD_FILE: /run/secrets/db_pass
    depends_on:
      - db
    networks:
      - wp_network

volumes:
  wp_data:
  db_data:

networks:
  wp_network:
    driver: bridge

secrets:
  db_root_pass:
    file: ./secrets/db_root_pass.txt
  db_name:
    file: ./secrets/db_name.txt
  db_user:
    file: ./secrets/db_user.txt
  db_pass:
    file: ./secrets/db_pass.tx
